---
# tasks file for apache_setup
- name: Install apache if not installed
  yum:
    name: "{{ package_name }}"
    state: present
- name: Update index.html file
  template:
    src: index.j2
    dest: "{{ root_dir }}/index.html"
  notify: reload_webserver
- name: Copy a text file to {{ root_dir }}
  copy:
    src: info.txt
    dest: "{{ root_dir }}/info.txt"
